### ISSUE TITLE
`src` 以下を別のレポジトリに分離

### ISSUE THREAD

**Issue by yudukikun5120** [Mimori256/kdb-parse#15]
## 動機

コード部とデータ部を分離した方が git clone 等の面で保守がしやすい。

## 目標

コード部（ `src/` ）を別のレポジトリ（ kdb-parse-core ）に移し、kdb-parse のワークフロー main.yml における src を使用している部分を kdb-parse-core に対する呼び出しとする。また、データのURL参照の互換性のためにコード部を分離する。

## 手順

1. kdb-parse-core レポジトリを作成し、それを @Mimori256 に譲渡する。
2.  kdb-parse から src ディレクトリを削除する。
3.  main.yml を次のように変更する。

```diff
   steps:
     - name: Checkout
       uses: actions/checkout@v2
+    - name: Checkout kdb-parse-core
+      uses: actions/checkout@v2
+      with:
+        repository: 'Mimori256/kdb-parse-core'
+        path: 'kdb-parse-core'
```

```diff
      - name: Synchronize the csv file with an up-to-date one
        run: |
-          python src/download.py
+          python kdb-parse-core/download.py
```

**Comment by yudukikun5120** [comment]
@Mimori256 レポジトリの transfer の要求を行ったので、確認をお願いします。

**Comment by Mimori256** [comment]
![image](https://github.com/Mimori256/kdb-parse/assets/80367947/c7e47a68-b831-470d-ad12-917eb74171b1)
ちょっと transfer の要求の通知が来ていない状況なので、transfer request の確認していただけると有り難いです...!
ソースコードを分離することには賛成です

**Comment by yudukikun5120** [comment]
![image](https://github.com/Mimori256/kdb-parse/assets/45707929/bddcaba0-1d7f-4b14-9381-89b9d553d92b)

@Mimori256 もう一度 transfer を要求しました。

**Comment by Mimori256** [comment]
移管できました。その他の作業については、今週中に対応します。

**Comment by Mimori256** [comment]
#17
https://github.com/Mimori256/kdb-parse-core/commit/b0a1a780e309cbd52f83b476e07feff4b01ebbf5

この変更で対応しました。
