### ISSUE TITLE
ワークフロー "CSV and JSON scheduled update" の Python バージョンのアップデート

### ISSUE THREAD

**Issue by yudukikun5120** [Mimori256/kdb-parse#16]
## 動機

kdb-parse-core において `|` 記法等の Python 3.10 以上にのみ対応した機能を用いているので、不都合が無ければ Python ランタイムのバージョンを 3.12 にまで引き上げたい。

## タスク
- [ ] ワークフロー "CSV and JSON scheduled update" 内の Python ランタイムのバージョンを 3.12 に上げる。

**Comment by Mimori256** [comment]
#17 で 3.12 まで上げました。
問題なく動いているのでこのままで大丈夫かと思います
